name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client mysql-server
          sudo pip install mysql-connector-python
          sudo mysql -u root -e "CREATE DATABASE world;"
          sudo mysql -u root -D "world" < *.sql
      - uses: education/autograding@v1
