name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo pip install mysql-connector-python
      - run: sudo systemctl start mysql.service
      - run: mysql -uroot -proot -e "CREATE DATABASE world;"
      - run: mysql -uroot -proot -D "world" < world_city.sql
      - run: mysql -uroot -proot -D "world" < world_country.sql
      - run: mysql -uroot -proot -D "world" < world_river.sql
      - uses: education/autograding@v1
