name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo pip install mysql-connector-python
      - run: sudo systemctl start mysql.service
      - run: sudo mysql -u root -e "CREATE DATABASE world;"
      - run: sudo mysql -u root -D "world" < *.sql
      - uses: education/autograding@v1
